restApi:
  port: '3000'
  baseUrl: 'http://localhost'
logLevel: 'info'
openAPI:
  license:
    name: ISC
    url: https://opensource.org/license/isc-license-txt/
mongodb:
  host: mongodb://localhost:27017/default
  options:
    useUnifiedTopology: 'true'
    connectTimeoutMS: 1000
    serverSelectionTimeoutMS: 5000
    keepAlive: true